apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secret
  namespace: scicat
spec:
  encryptedData:
    express-session-secret: ...
    jwt-secret: ...
    oidc-client-secret: ...
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: backend-secret
      namespace: scicat
    type: Opaque